### ISSUE TITLE
Error: Connection closed before message response was received.

### ISSUE THREAD

**Issue by purplemana** [ldapts/ldapts#1]
I tried to take this for a spin with a publicly available LDAP server. Older code with node-ldapauth-fork is running fine. With this package, I am getting an error. You can check the code and run it at https://repl.it/@purplemana/Ldapts. It's a copy-paste of the search example from the package's docs with the server details changed. You can get the ldap details here - https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/.

Here's the code for reference:

    const { Client } = require('ldapts');

    const url = 'ldap://ldap.forumsys.com:389';
    const bindDN = 'cn=read-only-admin,dc=example,dc=com';
    const password = 'password';
    const searchDN = 'ou=mathematicians,dc=example,dc=com';

    async function search() {
      const client = new Client({
        url
      });

      try {
        await client.bind(bindDN, password);

        const {
          searchEntries,
          searchReferences,
        } = await client.search(searchDN, {
          scope: 'sub',
          filter: 'cn=riemann',
        });

        console.log(searchEntries)

        return searchEntries;
      } catch (ex) {
        throw ex;
      } finally {
        await client.unbind();
      }
    }

    search()
    .then(console.log);

**Comment by jgeurts** [comment]
I'm able to replicate the ECONNRESET response from that provider. Working on getting it fixed and I'll push out a new version when I do get it resolved

**Comment by jgeurts** [comment]
@purplemana This should be fixed with release v1.1.2. Please let me know if you continue to have problems!

**Comment by purplemana** [comment]
Thanks @jgeurts.  It no longer hangs. Could you please help me understand how can I use the `filter` to find a user in my example? I tried the following values but no results are returned:

- cn=riemann
- (cn=riemann)
- uid=riemann
- (uid=riemann)
- (&(objectCategory=person)(objectClass=user)
(cn=riemann))

To check the available entries, please comment out the filter clause and you will see all the entries available within the dn.

**Comment by purplemana** [comment]
Thanks a ton @jgeurts!
