### ISSUE TITLE
Filtering by objectGUID 

### ISSUE THREAD

**Issue by sarus** [ldapts/ldapts#104]
Hello,

I'm trying to write a filter against the `objectGUID` attribute using the string representation of the GUID.  Based on the article here: https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5136 there is a pretty specific conversion that has to happen.

So in my case the objectGUID in string form is `F4C2CE4E-1F08-4358-ABDC-FE3F035AF4CD`.  According to the Microsoft documentation, to use this in a filter it needs to be converted to `\4e\ce\c2\f4\08\1f\58\43\ab\dc\fe\3f\03\5a\f4\cd` so the final filter becomes:

```
(objectGUID=\4e\ce\c2\f4\08\1f\58\43\ab\dc\fe\3f\03\5a\f4\cd)
```

Unfortunately, this isn't returning any records for me.  I just wanted to check and see if anyone has had success querying against the objectGUID field using the library.   I wanted to rule out the ldapts library doing anything behind the scenes that might change or render obsolete some of the conversion steps.

Thank you in advance for any suggestions or advice!

Best Regards,

Ed

**Comment by jgeurts** [comment]
It seems that both jumpcloud and forumsys do not expose objectGUID. I'm curious, when are you escaping the slash when specifying the filter?

Eg. 
```ts
const searchResult = await client.search('o=example,dc=example,dc=com', {
  filter: '(&(objectClass=*)(objectGUID = \\b5\\4a\\b3\\a6\\1b\\55\\26\\46\\b8\\ee\\2b\\36\\b3\\ee\\66\\72))',
});
```

**Comment by sarus** [comment]
Hi jguerts,

Thank you for your help.  I really appreciate it.  We're doing exactly what you have in your code snippet where we escape the the backslashes in the filter itself.

```
    const { searchEntries } = await client.search(options.searchDN, {
      scope: 'sub', 
      filter: '(objectGUID=\\4e\\ce\\c2\\f4\\08\\1f\\58\\43\\ab\\dc\\fe\\3f\\03\\5a\\f4\\cd)'
      sizeLimit: 1
    });
```

**Comment by johann-agilite** [comment]
I am getting this exact same issue, I am trying to query an AD record using the `objectGUID` in the filter properties. I have tried to do so in both the way mentioned above, with and without the `'objectClass=*'` and I also receive no searchEntries back.

**Comment by jgeurts** [comment]
I was using an openldap docker image to run a test server as part of #95. Maybe that could be used to recreate the issue.

**Comment by ErwSim** [comment]
Same here if you have any workaround

**Comment by ErwSim** [comment]
Managed to get it work with ldapjs and buffer on filter this way

filter: new ldapjs.EqualityFilter({
            attribute: 'ObjectGUID',
            value: Buffer.from(parsedGUID, 'hex')
          }),

where parsedGUID is formated https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5136 requests but without backslashes

Maybe ldapts could accept Buffer on filter

**Comment by jgeurts** [comment]
I added `Buffer` as a possible value type for EqualityFilter. Could you give v3.1.0 a shot if you have a chance?

**Comment by ErwSim** [comment]
I can confirm it solved the issue @jgeurts 
Thank you :)
