### ISSUE TITLE
Expose Socket lifecycle methods

### ISSUE THREAD

**Issue by mattmahn** [ldapts/ldapts#105]
Can we get the underlying `net.Socket`'s `socket.end()`, `socket.unref()`, and `socket.ref()` methods exposed in the `Client` class.
An example use case would be using it in a script so that the script ends automatically:
```js
import * as ldapts from 'ldapts';

(async () => {
	const ldapClient = new ldapts.Client({ url: 'ldaps://ldap.example.com' });
	ldapClient.unref();
	await ldapClient.bind(config.get('ldap.accessDN'), config.get('ldap.password'));

	const results = await ldapClient.search(`DC=example,DC=com`, {
		filter: `sAMAccountName=AzureDiamond`,
	});
	console.log(results);
})();
```

**Comment by jgeurts** [comment]
Hi @mattmahn, sorry for the delay. I'm game to expose those methods, but I'm not sure I completely see the use case. 

`socket.end()`:

The socket will end when calling `await ldapClient.unbind();`. That will clean up some event handlers as well. 

`socket.ref()` and `socket.unref()`:

With your example, if the bind was successful, then the socket would prevent the application from exiting. I think that would be the same behavior as `.ref()`. When `.unbind()` is called, that would destroy the socket and allow the application to exit. I believe that might fill the use case for `.unref()`.

Please let me know if I'm misunderstanding or missing something!

**Comment by mattmahn** [comment]
Turns out the minimal use case I posted above was a bit too minimal 😅

My exact scenario, being in a web server, is a bit more complicated that this example script.  On further thought, this would be more idiomatic to be handled by a "shutdown hook" system along the lines of
```js
class LDAPService {
  constuctor() {
    this.client = new ldapts.Client(/* stuff */)
    process.once('SIGINT', () => this.client.unbind())
    process.once('SIGTERM', () => this.client.unbind())
  }
}
```
