### ISSUE TITLE
@types/nodes version in `dependencies` in `package.json`

### ISSUE THREAD

**Issue by thernstig** [ldapts/ldapts#108]
https://github.com/ldapts/ldapts/blob/a79f86e7aa0ddd3f7bec7405450199278496dab3/package.json#L51

As can be seen, it requires Node.js 16.x If a user using 17.x installs `@types/node` it means their could be incorrectness in types.

Instead this could be done similar to e.g. `@types/asn1` itself includes `@types/node`:
https://github.com/ldapts/ldapts/blob/a79f86e7aa0ddd3f7bec7405450199278496dab3/package-lock.json#L210

Or possibly `>=16.11.7`.

In my huge package-lock.json file, all of them do either of those two. Using a star or equal-or-greater than. Except ldapts which fixes the MINOR version.

**Comment by jgeurts** [comment]
I think v3.2.1 should fix this. Please let me know if that's not the case!
