### ISSUE TITLE
Cannot upload binary data to OpenLDAP server

### ISSUE THREAD

**Issue by vfosnar** [ldapts/ldapts#114]
I am using this client to manage user data on my OpenLDAP server. The `;binary` subtype does not work, so I must use `explicitBufferAttributes` like this (this code works):
```
attributes: ['givenName', 'sn', 'uid', 'mail', 'jpegPhoto'],
explicitBufferAttributes: ['jpegPhoto'],
```

But when uploading an image it throws this error: `UndefinedTypeError: jpegPhoto;binary: option "binary" not supported with type Code: 0x11`.

I would really appreciate some help

**Comment by jgeurts** [comment]
I tried removing auto appending `;binary` to the attribute name when a buffer is detected. Could you please give [v4.1.0-beta1](https://www.npmjs.com/package/ldapts/v/4.1.0-beta1) a shot?

**Comment by vfosnar** [comment]
Yes! it worked. Thanks
