### ISSUE TITLE
Error in attribute conversion operation

### ISSUE THREAD

**Issue by pasekit** [ldapts/ldapts#118]
Try to create a user but getting always an attribute conversion error. tested with an Microsoft ActiveDirectory (Windows Server 2016)

ldapts: 3.2.3
node.js: 16.13.1

```
const attributes = {
				cn: 'firstname  lastname',
				objectclass: ['organizationalPerson', 'person', 'top'],
				pwdReset: 'TRUE',
				givenName: 'firstname',
				sn: 'lastname',
				userPassword: "Test123!!"
			};
await this.client.add("CN=Test-user,OU=Test,DC=test,DC=int", attributes);
```

Getting this error:

```
Error: 00000057: LdapErr: DSID-0C0910F4, comment: Error in attribute conversion operation, data 0, v4563 Code: 0x10
    at Function.parse (C:\Apps\PASEK\Backend\node_modules\ldapts\StatusCodeParser.ts:68:16)
    at Client.add (C:\Apps\PASEK\Backend\node_modules\ldapts\Client.ts:334:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jgeurts** [comment]
Hi, unfortunately, I do not have an environment to replicate the issue. Please let me know if you are able to provide a replication and I'll happily assist in fixing the code.

**Comment by pasekit** [comment]
Unfortunately, I don't know how you can rebuild the environment without a Windows domain controller.
But can you tell me if the syntax would be correct in principle?

**Comment by pasekit** [comment]
I was able to fix the problem. it was two errors combined. Once the attribute was wrong and it had to be a secure connection (ldaps) to create an object.
then there was the error that the cn attribute had to match the one in the distinguished name.

this is what works now (with secure ldap):
```
const attributes = {
	cn: 'mytest',
	objectclass: ['person', 'top', 'user'],
	givenName: 'firstname',
	sn: 'lastname',
	unicodePwd: this.encodePassword("Test123!!"),
	sAMAccountName: "mytest",
	userPrincipalName: "mytest@test.int",
};
await this.client.add("CN=mytest,OU=Test,DC=test,DC=int", attributes);
```
