### ISSUE TITLE
Unsupported Nullish Coalescing on older versions of Node

### ISSUE THREAD

**Issue by ericsienk** [ldapts/ldapts#119]
Could you compile this library with a target of es2019? I would really like to use ldapts in a CLI, but not all my users have a version of node that supports the `??` operator. Thanks!

https://github.com/ldapts/ldapts/blob/19e8bed649967556efe8a5d6caa910e41f9d3aea/tsconfig.json#L3

**Comment by jgeurts** [comment]
Hi @ericsienk,

es2020 should be supported by all node 14+. Any earlier versions of node are not supported. That said, [version 3.2.4](https://github.com/ldapts/ldapts/releases/tag/3.2.4) of ldapts does support es2019 as a target. Hope that helps!
