### ISSUE TITLE
how to modify ? 

### ISSUE THREAD

**Issue by jedsad5** [ldapts/ldapts#12]
hello
     please to help me.  when i call modify function required Change but when i import it and console log to check is undefined
    when i new Change , Attribute 
-> TypeError: _ldapts.Change is not a constructor
-> TypeError: _ldapts.Attribute is not a constructor

--> my code <--
import { Client, Change, Attribute } from 'ldapts'
...
const mod = new Attribute({
      type: 'info;string',
      values: [ 'zzz']
    })

--> and error return <--
UnhandledPromiseRejectionWarning: TypeError: _ldapts.Attribute is not a constructor

can you help me resolve this issue ,

Thank you very much

**Comment by jedsad5** [comment]
after i mod ldapts/dist/index.js

__export(require("./Client"));
__export(require("./Attribute"));
__export(require("./Change"));

new i can use modify with Change and Attribute to modify ldap data

but i not sure this is correct way to use it ?

**Comment by jgeurts** [comment]
Hi, sorry about the delay in getting back to you. I continue to have problems getting notified of new issues unless directly mentioned, unfortunately. 

Please have a look at https://github.com/ldapts/ldapts/blob/master/tests/Client.tests.ts#L185-L194 - it shows how to call modify. If you have additional questions, please let me know!

**Comment by keviv164** [comment]
@jgeurts I am having the same issue 
-> TypeError: _ldapts.Change is not a constructor
-> TypeError: _ldapts.Attribute is not a constructor

The test that is referred to in the earlier comment https://github.com/ldapts/ldapts/blob/master/tests/Client.tests.ts#L185-L194  is commented out.

**Comment by jgeurts** [comment]
With v1.9.0 pushed out, does something like the following work for you?

```
import { Client, Change, Attribute } from 'ldapts';


export async function test(thumbnailPhotoBuffer: Buffer) {
  const client: Client = new Client({
    url: 'ldaps://ldap.jumpcloud.com',
  });

  await client.bind('foo', 'bar');

  try {
    await client.modify('uid=groot,ou=Users,dc=foo,dc=com', new Change({
      operation: 'replace',
      modification: new Attribute({
        type: 'thumbnailPhoto;binary',
        values: [thumbnailPhotoBuffer],
      }),
    }));
  } finally {
    await client.unbind();
  }
}
```

**Comment by keviv164** [comment]
Sorry for the delay. It works fine with 1.9.0. Thank you :)
