### ISSUE TITLE
How to handle paged search

### ISSUE THREAD

**Issue by deusilva** [ldapts/ldapts#125]
Hi @jgeurts !

FIrst, thanks for the lib! Its beeing very useful for me!

Can you make any documentation on how can we handle paged results?

I want to list the entries in a table with pagination but i could not achieve how to do this on LDAP.

I manage the LDAP with `Apache Directory Studio` and i can search with pagination but i could not achieve this with the lib.

I know that de **search** method have a option to limit the `pageSize` and `sizeLimit` but i do not know how i can inform the current page.

Thanks in advance for the attention and pacience!

**Comment by jgeurts** [comment]
I think, unless I'm mistaken, that ldap does not support specifying a specific page to return results. The paging supported is more to suggest to the server how many results to return in separate responses. It's kind of an all or nothing. 

If I'm wrong about that, I'd be happy to update the library!

**Comment by deusilva** [comment]
Understood. When i saw the `pageSize` on `search` i was hopeful. But I did a research this days about that and i couldn't find anything about pagination in LDAP. Its a weird limitation. Why exists the `PagedResultsControl` if the results are not paginated in practice?

Oh well, anyway, thanks again for the pacience, attention e for this awesome lib!
