### ISSUE TITLE
Add method for iterating on search results pages as they're received

### ISSUE THREAD

**Issue by adam-in-ict** [ldapts/ldapts#126]
We recently hit a limit on a server with a search requesting more than the server's size limit of 1000 entities.  Adding a pageSize below that threshold fixed our issue, but brought up a bigger question.  My current understanding is that the page size shrinks the individual payloads requested from the server, but we will still receive them all back as one large result from the `search` function.

I looked at passing a `PagedResultsControl` control parameter to the `search` function so that I would have access to the number of returned entities and the cookie for the next set of results, but was given an error that I should not be specifying a `PagedResultsControl` to that function.

It would be great if the functionality were added to be able to process pages as they come in so that the total search results don't have to fit in memory.

**Comment by jgeurts** [comment]
Hi, thank you for your message! I apologize for not replying sooner, but I have been thinking about some solutions for this. I'll try to whip something up over the next couple weeks

**Comment by PaulSchult** [comment]
Hey, @jgeurts anything new on this topic? Would be really stoked to have pagination.
