### ISSUE TITLE
Connection closed before message response was received. Message type: BindRequest (0x60)

### ISSUE THREAD

**Issue by viv578ek** [ldapts/ldapts#128]
React-Native library using setup LDAP 
[react-native-ldapts](https://github.com/minkuan88/react-native-ldapts) 

React-native 
react-native-cli: 2.0.1
node : - v18.5.0
react-native": "^0.62.2"

 I am trying to connect  server  still getting error 
**-------> Connection closed before message response was received. Message type: BindRequest (0x60)**

   // Request  &. Setup:
   import { Client } from 'react-native-ldapts/Client';

const url = 'ldap://ldap.********:123';
const bindDN = 'cn=xxxx,dc=xxxxxx,dc=xxxx,dc=xxx';
const password = 'xxxxxxxxxxxxxxxxxx';
const searchDN = 'XXXX,dc=XXXX,dc=XXX';

//////request Init Setup *******************
const client = new Client({
            url,
          });
          
          try {
            await client.bind(bindDN, password);
          
            //const { searchEntries, searchReferences } = await client.search(searchDN);
            //console.log("searchEntries&*******", searchEntries)
            //console.log("searchReferences&*******", searchReferences)

          } catch (ex) {
            console.log("isAuthenticated*******************", ex);
            throw ex;
          } finally {
            console.log("isAuthenticated*******************");
            await client.unbind();
          }

Result Error ->. 

      socket-0 _read
     socket-0 Socket._read resume
     socket-0 connecting, host: ldap.xxxx.xxxxxxx.xxx port: xxx
    {"details": {"bssid": null, "ipAddress": "000.000.000.000", "isConnectionExpensive": false, "ssid": null, "subnet": "000.000.000.000"}, "isConnected": true, "isInternetReachable": true, "type": "wifi"}
    socket-0 received connect
socket-0 received close
isAuthenticated******************* [Error: Connection closed before message response was received. Message type: BindRequest (0x60)]
 isAuthenticated*******************

NOTE: - Connection closed before message response was received. Message type: BindRequest
Please help Me Is any one solution for React-Native Application

**Comment by jgeurts** [comment]
Hi, you may have better luck reaching out to the [react-native-ldapts](https://github.com/minkuan88/react-native-ldapts) project. They may be able to provide more insight into connection errors from devices.

**Comment by viv578ek** [comment]
I have posted same the [react-native-ldapts](https://github.com/minkuan88/react-native-ldapts)
