### ISSUE TITLE
'Socket connection not established' when server closes connection

### ISSUE THREAD

**Issue by trevh3** [ldapts/ldapts#13]
I'm encountering the 'Socket connection not established' error located at the top of the _send function in Client.js. This will occur when this.connected == true, but this.socket == undefined. We land here because (for example) the search function will only call _connect if this.connected == false, not if this.socket is undefined.

To reproduce:
1. Start server
2. Have client make a query. This sets this.connected = true and defines the socket
3. Have the server gracefully close the connection.
4. Have client make another query.

I believe root cause occurs in the socketClose function and the connectTimer timeout, where the socket is deleted, but this.connected is not set to false

**Comment by jgeurts** [comment]
Merged and pushed out v1.4.1. Thanks for the help!
