### ISSUE TITLE
`OrFilter#toString` returns `filter.constructor.name` instead of correct values

### ISSUE THREAD

**Issue by ryanlsimms** [ldapts/ldapts#145]
[this change](https://github.com/ldapts/ldapts/commit/f2887b9bd5e654ce2937517ea75d39448954b230#diff-f13e6bf547ede19703e9c12cef1391367112ba081a98dcc857dd7a4276eb4a7dR46) from 6.0.0 (along with the same in the `NotFilter` seems to be a mistake, as it will return something like `(|EqualityFilterEqualityFilter)` instead of `(|(employeeType=FTE)(employeeType=PTE))`
It looks like there are no tests which would have caught this.

**Comment by jgeurts** [comment]
Thank you for letting me know! It is fixed in v7.0.4. Please open a new issue if things aren't working as expected with that version.
