### ISSUE TITLE
TLS 1.3 not supported

### ISSUE THREAD

**Issue by jelhub** [ldapts/ldapts#152]
Testing Active Directory

```
import { Client } from 'ldapts'

const client = new Client({
  url: 'ldaps://ad.test.com:636',
  connectTimeout: 5000,
  tlsOptions: {
    rejectUnauthorized: false
  }
})

client.bind('CN=Administrator,CN=Users,DC=test,DC=com', 'password')
  .then((res) => {
    console.log('OK')
  })
  .catch((err) => {
    console.log('bind error: ' + err.message)
  })
```

Domain controller only allowing TLS 1.3

![image](https://github.com/ldapts/ldapts/assets/11636556/9fe329c5-acd4-4766-bf29-6849f3d30ca4)

TLS 1.3 only test will fail: ECONNRESET
![image](https://github.com/ldapts/ldapts/assets/11636556/52d88aa3-4472-4dea-af82-50e78237d317)

TLS 1.2 appears to be the most advanced TLS version supported:
![image](https://github.com/ldapts/ldapts/assets/11636556/3bdf1387-46ca-4e48-aab3-3317ff7a20c3)

**Comment by thernstig** [comment]
@jelhub are you sure this is an ldapts fault? I recon TLS negotiation is done by the underlying engine e.g. Node.js and should thus be supported.

Could it be that you have set the "Client Protocols" to TLS 1.3, but that the Node.js TLS client sends a negotation about the protocol and includes TLS 1.2 ciphers etc, and it fails because the server expects only TLS 1.3 ciphers, or something along those lines?

I am _guessing_ quite heavily here, but reacted to that it would be a ldapts fault.

**Comment by jelhub** [comment]
@thernstig,
Example code mentioned is using ldapts only functionality.
I have not looked into details on how ldapts do TLS with regards to nodejs

New solutions seem to have TLS 1.3 preferred.
One example is Bun (by the way failing when using ldapts)

You may close this issue if you think it’s out of scope.

Thanks

**Comment by thernstig** [comment]
> New solutions seem to have TLS 1.3 preferred.

Could you elaborate what you mean here?

I do not think it is out of scope, but I am having a hard time seeing it is related to the ldapts code. ldats uses the 'tls' package from Node.js, and uses a [`tls.connect()`](https://nodejs.org/api/tls.html#tlsconnectoptions-callback) to connect to the server. That supports TLS 1.3 depending on your Node.js version.

**Comment by jelhub** [comment]
@thernstig,
SSL is outdated
TLS 1.0 and 1.1 is outdated (soon to be disabled in Windows)
TLS 1.2 soon to be outdated...
TLS 1.3 is the most current version

Bun prefers TLS version 1.3 (and have fallback to older versions). This is also explicitly stated in Bun's roadmap, where it mentions support for "TLS 1.3 0-RTT" as part of its security and performance enhancements​​. Bun's focus on modern features includes ensuring compatibility and optimal security with the latest TLS version, which is TLS 1.3.

Ref:
https://github.com/oven-sh/bun/issues/159
