### ISSUE TITLE
Filter disabled users on AD

### ISSUE THREAD

**Issue by xelandreb** [ldapts/ldapts#16]
I have just migrated from ldapjs and appreciate changes and corrections made on the code. Nevertheless, a filter using previously with ldapjs not work. It's normaly should remove desactivate users on AD (see last part of filter below). 
```
const searchOptions = {
            scope: 'sub',
            sizeLimit: 50,
            attributes: ["sAMAccountName", "name", "mail", "telephoneNumber", "sn", "givenName"],
            filter: '(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))'
        };
```
Without userAccountControl Filter, I've got all users but with I've an empty result.

**Comment by jgeurts** [comment]
Thanks for sending this. I’ll need to make a couple tests to see what this project is doing differently.

**Comment by jgeurts** [comment]
Thanks for your patience with this! I'm going to release v1.5 shortly and that has a minor fix for ExtensibleFilterControls that I hope fixes your issue. If it does not fix things, if you could create a failing test, that would help me considerably. Extensible filters are complex and I don't have a ton of experience using them.

**Comment by xelandreb** [comment]
Thanks for your work but i've just tested 1.5 and same problem always occurs. 

Moreover, I thinks there is a regression because in 1.5, I've got error that not producing in 1.4.2 (same code) :

```
LDAP request error { Error: There were more entries matching the criteria contained in a SearchRequest operation than were allowed to be returned by the size limit configuration. Code: 0x4
    at Function.parse (C:\Users\abenard\Documents\Repos\RouteManager\node_modules\ldapts\src\StatusCodeParser.ts:52:16)
    at Client._sendSearch (C:\Users\abenard\Documents\Repos\RouteManager\node_modules\ldapts\src\Client.ts:540:30)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  code: 4,
  message:
   'There were more entries matching the criteria contained in a SearchRequest operation than were allowed to be returned by the size limit configuration. Code: 0x4' }
```

**Comment by jgeurts** [comment]
Apologies about that! I'll see if I can get a couple tests to reproduce the behavior. If, in the mean time, you're able to reproduce it with the jumpcloud credentials in the tests or the forumsys publicly available ldap server, that would help a bunch.

**Comment by jgeurts** [comment]
I pushed out v1.5.1. That has a change to disregard the `Size limit exceeded` response from a server when `sizeLimit` is specified. I'm honestly not sure what to do in that case as it appears that results are still sent back, but the server sends the `Size limit exceeded` response. With the two test ldap servers I have access to, they both behaved the same, where I got back the number of results I expected. The unfortunate part is that there's no real way of letting the ldapts client know that the server threw `Size limit exceeded`.

As for the `userAccountControl` query, I don't believe I'm able to reproduce that with JumpCloud or forumsys' ldap servers. I couldn't get JumpCloud to return a record using a similar query, even with the `ldapsearch` command. forumsys said that the attribute was not valid. If you can reproduce what you're seeing with an `ldapsearch` command, I can make a test and look into that further.

**Comment by jgeurts** [comment]
Looks like I was unnecessarily escaping filter names & values. Can you please try v1.6.0 and see if that resolves your issue?

**Comment by lennarkivistik** [comment]
I can confirm this works now.
user is not listed when disabled and reappears once enabled in Active Directory

**Comment by jgeurts** [comment]
Great, thanks for letting me know! Glad it’s working for you!

**Comment by xelandreb** [comment]
Thanks a lot. It works perfectly !
