### ISSUE TITLE
Escaping filters & distinguished names

### ISSUE THREAD

**Issue by adrianplavka** [ldapts/ldapts#2]
First of all, I want to thank you for this repository. We switched our project's LDAP implementation from `ldapjs` to yours and it seems to be working just fine. Being a TypeScript project, it's just a cherry on top.

However, quickly glancing over the code, I couldn't find escaping mechanism of certain characters to prevent [LDAP injections](http://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx).

Is there any way of incorporating this into the project? Right now, it seems that I am forced to use [ldap-escape](https://github.com/tcort/ldap-escape) library.

**Comment by jgeurts** [comment]
Sorry for the slow reply - not sure why I don’t get notified unless specifically tagged. Anyway, I do have some escape logic for filters: https://github.com/ldapts/ldapts/blob/master/src/filters/Filter.ts#L36

I’m pretty sure that I don’t escape DN strings, however. I can look to adding that for the next release. Thank you for bringing this up and providing those links!

**Comment by adrianplavka** [comment]
No worries, thanks for the clarification!

About the notification issue, try to follow this [StackOverflow answer](https://stackoverflow.com/a/10560931/8484638). Since this is not directly your own repository (but rather an organization's), then it might be causing some issues.
