### ISSUE TITLE
LDAP_MATCHING_RULE_IN_CHAIN yields no result

### ISSUE THREAD

**Issue by stiller-leser** [ldapts/ldapts#21]
Hi @jgeurts,

it's me - again ;) 

I am currently testing the following ldap query `(&(objectClass=user)(displayName=SomeIdentifier)(memberOf:1.2.840.113556.1.4.1941:=CN=A Parent Group))` to search for a user in a group that contains many children groups. According to [https://docs.microsoft.com/en-us/windows/desktop/adsi/search-filter-syntax](this) `1.2.840.113556.1.4.1941` translates into a `LDAP_MATCHING_RULE_IN_CHAIN`.

The query gets correctly translated into a big `AndFilter` with three filters by ldap ts:

```
AndFilter {
  type: 160,
  filters: [
    EqualityFilter {
      type: 163,
      attribute: 'objectClass',
      value: 'user'
    },
    EqualityFilter {
      type: 163,
      attribute: 'displayName',
      value: 'SomeIdentifier'
    },
    ExtensibleFilter {
      type: 169,
      matchType: 'memberOf',
      rule: '1.2.840.113556.1.4.1941',
      dnAttributes: false,
      value: 'CN=A Parent Group'
    }
  ]
}
```

Checking the buffer in the `SearchRequest` it seems that it gets at least written into the stream correctly (even though one can't see much):

```
�b�
   objectClassuser�
                   displayNameSomeIdentifier�3�1.2.840.113556.1.4.1941memberOf�CN=A Parent Group0LLL
```

Using the following ldapsearch I get a result:

`ldapsearch -H ldaps://myldapserver.com -x -w 'verySecret' -D 'myUser' -b 'DC=global,DC=corp,...' "(&(objectClass=user)(displayName=SomeIdentifier)(memberOf:1.2.840.113556.1.4.1941:=CN=A Parent Group))"`

Would be awesome if you could look into this. As always: More than happy to help!

Regards,
stiller-leser

**Comment by jgeurts** [comment]
If you can please reproduce this with a publicly available ldap server, that is the only way I'll be able to fix this. If that's possible, please re-open this issue
