### ISSUE TITLE
Any plans to port over server functionality?

### ISSUE THREAD

**Issue by nickzelei** [ldapts/ldapts#23]
I just stumbled across this project and it looks promising. The ldapjs codebase has been dead for quite a while now and it's great to see some movement again.

I see that this only uses the client functionality from ldapjs, is there any plans to bring over the server functionality from it?

My team runs an internal ldap proxy and we use ldapjs. We currently have an internal fork of it to fix some server bugs that have/will never been fixed in ldapjs. It would be great to switch over to this library (we also use TypeScript) and to potentially push some of our fixes upstream as well.

**Comment by hongkongkiwi** [comment]
I was also keen to use the server functionality. ldap is so core and supported by so many frontend auth solutions that it would be great to unify with a modern ldap server.

Perhaps we could get a list going of the core functionality we'd need for the server to be useful and go from there.

**Comment by jgeurts** [comment]
I'm open to accepting PRs for a server implementation. The main reason I haven't done so is that I only needed client functionality.

**Comment by zelein** [comment]
Understandable. I think there is currently space for a fresh ldap server implementation that frees everyone up from ldapjs.
