### ISSUE TITLE
Error on connection

### ISSUE THREAD

**Issue by GCSBOSS** [ldapts/ldapts#24]
```
Unhandled Exception TypeError: Cannot read property 'removeAllListeners' of undefined
     at Client._onConnect (/usr/src/app/node_modules/ldapts/Client.js:456:21)
     at Socket.socket.once (/usr/src/app/node_modules/ldapts/Client.js:431:26)
     at Object.onceWrapper (events.js:273:13)
     at Socket.emit (events.js:187:15)
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1149:10) undefined
```

Getting this error on trying to connect. Let me know if you guys need some specifics.

**Comment by december1981** [comment]
This is happening for me, too, and, from a cursory glance at Client.js I'd say (and I'm hazarding a guess here as I've never touched nor looked at this code before)...

A bind operation is called, which results in ```_connect``` being called. ```_onConnect``` is called when connected and the underlying socket is marked as ```this.connected = true```.

So let's say an unbind operation happens, which marks the socket as ```this.connected = false``` in the ```_send``` handler, ends the socket with ```this.socket.end()```. Eventually ```socketClose``` will be called (which does a ```delete this.socket``` at some point.)

But suppose a new bind and ```_connect``` happens before ```socketClose```, and ```_onConnect``` is scheduled again (which it will be as ```this.connected``` was marked as false in the unbind ```_send``` handler). Then suppose the ```socketClose``` from the previous ```this.socket``` that was ended occurs just before ```_onConnect``` ... it will delete the latest ```this.socket``` ... So when ```_onConnect``` kicks in, it will have a ```this.socket``` which has just been deleted, and for which case it does not handle...
