### ISSUE TITLE
More DOCs please

### ISSUE THREAD

**Issue by intervalia** [ldapts/ldapts#31]
It would be real nice if there were documentation for all functionality.

The current docs do not discuss features like add, change, etc. And I just have no clue how to use them.

**Comment by tfrancois** [comment]
Thank you...very interested in the same.  Looking to migrate from ldapjs and this implementation is not a drop-in replacement it seems (via my own testing) so it would be helpful to know what changes need to take place in existing ldapjs-dependent solutions to retrofit to this newer (thank you btw!) version that I heard resolves the current issues with nodejs 10 and ldapjs.

Please just a few more documentation snippets!  Thanks again.

**Comment by jgeurts** [comment]
Apologies this took so long... Hopefully the documentation update helps!

**Comment by intervalia** [comment]
Thank you. Excellent additions to the Docs. Greatly appreciated.
