### ISSUE TITLE
Modify Multiple Attributes at once

### ISSUE THREAD

**Issue by colmbegs89** [ldapts/ldapts#34]
is there a way to modify multiple attributes in a single change e.g. below 
`  await client.modify(SEARCHCRITERIA'', new Change({
      operation: 'replace',
      modification: new Attribute(
        {
        type: 'title',
        values: ['web tester']
      },
        {
        type: 'displayName',
        values: ['John W Doe']
      }
      ),
    }));
`

or

`  await client.modify(SEARCHCRITERIA'', new Change({
      operation: 'replace',
      modification: new Attribute(
        {
        type:[ 'title','displayName']
        values: ['web tester','John W Doe'],
      }
     ),
    }));
`

**Comment by intervalia** [comment]
Or even like this:

```
await client.modify('SEARCHCRITERIA', new Change({
  operation: 'replace',
  modification: [
    new Attribute({
      type: 'title',
      values: 'web tester'
    }),
    new Attribute({
      type: 'displayName',
      values: 'John W Doe'
    })
  ]
}));
```

or this:

```
await client.modify('SEARCHCRITERIA', new Change({
  operation: 'replace',
  modification: new Attribute([
    {
      type: 'title',
      values: 'web tester'
    },
    {
      type: 'displayName',
      values: 'John W Doe'
    }
  ])
}));
```

**Comment by jgeurts** [comment]
It doesn't seem that ldap supports modifying multiple attributes as part of a single change statement, but you can modify multiple change statements as part of a single modify call:

```
await client.modify('SEARCHCRITERIA', [
  new Change({ operation: 'replace', modification: new Attribute({ type: 'title', values: ['web tester'] })),
  new Change({ operation: 'replace', modification: new Attribute({ type: 'displayName', values: ['John W Doe'] })),
]);
```

Please let me know if that helps!

**Comment by colmbegs89** [comment]
@jgeurts  really sorry for the late reply, that was the perfect answer, cheers!
