### ISSUE TITLE
DN has embedded parentheses

### ISSUE THREAD

**Issue by bobweil** [ldapts/ldapts#35]
I search a group to retrieve the paths for each user in the group, then query each using that path as the distinguished name.  Unfortunately, some of the DN entries contain embedded parentheses like this:
`CN=Joe Cool (contractor),CN=Users,DC=myco,DC=mycompany,DC=com
`
These parentheses choke the filter parser in ldapts.  I've tried various schemes for escaping them, but still get rejections from ldapts.  These are legal characters for LDAP, how can I get these past the filter parser in ldapts?

**Comment by rgmz** [comment]
Hi @bobweil,

You should be able to use the built-in filter to accomplish this:

```javascript
const { Filter } = require( 'ldapts/filters/Filter');
const userDn = new Filter().escape('CN=Joe Cool (contractor),CN=Users,DC=myco,DC=mycompany,DC=com');
console.log(userDn);
```

**Comment by bobweil** [comment]
Thanks for that.  Where can I find API documentation that describes this?  I've checked out lpdapjs as well and while it acknowledges the existence of Filter objects, it does not describe them.
