### ISSUE TITLE
Error types are not exported

### ISSUE THREAD

**Issue by CDoughty08** [ldapts/ldapts#4]
There is not an easy way to import the Error classes for checking in exception handling, having to do `import { InvalidCredentialsError } from 'ldapts/dist/errors/resultCodeErrors/InvalidCredentialsError'`.

Would it be reasonable to export these from the index.d.ts?

**Comment by jgeurts** [comment]
Just pushed v1.2.1 with exports for error, filter, and message classes. Hope that helps! If you had something else in mind, please let me know
