### ISSUE TITLE
Reconnection policy

### ISSUE THREAD

**Issue by adrianplavka** [ldapts/ldapts#5]
As it goes with external services, if the service goes temporarily unavailable (by closing the socket), the client will not try to reconnect again. 

With the current API, it is not possible, to define custom event handlers for implementing a reconnection policy.

My proposed suggestion would be (similar to `ldapjs` package), to have a new object setting in `ldap.Client`'s constructor named `reconnection`, which would define, if the reconnection should be enabled & intervals for automatic reconnection.

The next solution (which could, by the way, exist with the previous solution) would be to extend client as an `EventEmitter` object. That way, users of this library could extend event behavior to their liking.

**Comment by jgeurts** [comment]
I'm open to a pull request :) I've been holding off on making the client an EventEmitter, unless it's needed, to keep the usage as simple as possible.
