### ISSUE TITLE
Error: Could not find declaration file for module 'asn1'

### ISSUE THREAD

**Issue by Ashniu123** [ldapts/ldapts#6]
I am making a program in TS and while building this error pops up. Any idea why?

```
node_modules/ldapts/dist/filters/Filter.d.ts:2:38 - error TS7016: Could not find a declaration file for module 'asn1'. '.../node_modules/asn1/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/asn1` if it exists or add a new declaration (.d.ts) file containing `declare module 'asn1';`

2 import { BerReader, BerWriter } from 'asn1';
```
Same error also occurs for other `.d.ts` files like `Attribute.d.ts`, `Change.d.ts`, `Control.d.ts`

Btw there is no types for [asn1](https://www.npmjs.com/package/asn1)

@jgeurts @adrianplavka

**Comment by jgeurts** [comment]
Hrm... odd. I did have to create type definitions for asn1. Maybe you can add them to your tsconfig? https://github.com/ldapts/ldapts/blob/master/src/%40types/asn1.d.ts

**Comment by adrianplavka** [comment]
I can not reproduce it with my current setup, it all seems fine. Can you clarify which version of ldapts do you use? 

@jgeurts Since the typings for the asn1 do not exist yet, what about adding them to the @types?

**Comment by jgeurts** [comment]
Im working on adding the types to definitely typed. That should help others in these situations!

**Comment by Ashniu123** [comment]
> I can not reproduce it with my current setup, it all seems fine. Can you clarify which version of ldapts do you use?
> 
> @jgeurts Since the typings for the asn1 do not exist yet, what about adding them to the @types?

I'm using v1.2.2 of ldapts which is the latest version right now.

> Im working on adding the types to definitely typed. That should help others in these situations!

That would resolve this issue. Thanks!

**Comment by jgeurts** [comment]
I have a PR to DefinitelyTyped to add the types. It sounds like it takes a couple days to be approved, but it should be there shortly. You can follow progress at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32634

**Comment by jgeurts** [comment]
@Ashniu123, the PR with DefinitelyTyped was approved and I pushed out v1.2.3 that references the asn1 types from there. Hope that helps!
