### ISSUE TITLE
TypeError: Invalid data, chunk must be a string or buffer, not object

### ISSUE THREAD

**Issue by bensventures** [ldapts/ldapts#7]
This is not a bug report per se, I just wanted to share something that got me stuck with my current setup and maybe open a discussion about a PR.

I was getting this error when trying to bind to the ldap server given in the bind example:
```
TypeError: Invalid data, chunk must be a string or buffer, not object
at Socket.write (net.js:704:11)
at Client._send (app/server.js:22724:21)
at Client._sendSearch (app/server.js:22549:35)
at Client.search (app/server.js:22531:20)
```

After some investigation I identified the `asn1` lib used to create the buffer from the message as being the problem. Internet told me it is barely maintained anymore and offered `asn1-ber` as a dropin replacement. I made an alias in my webpack config to not modify anything and it started working straight away:
```
resolve: {
        alias: {
            'asn1': 'asn1-ber'
        },
}
```
I'm not sure if there is any downside to using the alternative lib but the author says there isn't. Seems to be working for me and my particular setup (Meteor.js). But if other people are having the same problem it might justify a change directly in `ldapts` rather than the webpack workaround.

Great lib in any case, works like a dream, thank you so much.

**Comment by jgeurts** [comment]
Hmm... I wonder if I defined something wrong when creating the type definition for asn1. I'm not married to that library, I used it because it is what ldapjs used. 

Is there any way that you could find some more info about what type of object was sent to which asn method?

**Comment by jgeurts** [comment]
If you're able to make a reproduction with a unit test, that would be awesome. If you look in the unit tests, I use some live ldap servers. Hopefully those allow you to reproduce what you're seeing.

**Comment by bensventures** [comment]
I'll look into it and get back to you 👍

**Comment by bensventures** [comment]
So after doing testing I cannot reproduce the error on a clean setup with node 11 or 8. I am now thinking the problem might come from the old version of Node (4.8.1) I am using in this project or the babel transpiling that happens in the middle.

Provided that this repo requires node >= 8.11 it's really an issue with might particular setup and nothing to do with the code. I'm long overdue for a Meteor upgrade anyway 😄 

Closing the issue 👍
