### ISSUE TITLE
Implement StartTLS

### ISSUE THREAD

**Issue by thomascmurphy** [ldapts/ldapts#71]
This would be a huge benefit for us, as only simple auth is supported at the moment we will have to require an ldaps connection. I just tested out using starttls with the ldapjs library and it seems that it would fix our issue and allow plain ldap connections once again. I would love to continue using ldapts in our project but for now I may have to just wrap the ldapjs stuff :(

**Comment by jgeurts** [comment]
I'm curious about the use case for having a `startTLS()` method vs specifying the `tlsOptions` when creating the client.

**Comment by thomascmurphy** [comment]
Oh hopefully I'm just missing something that I can overcome with settings, that'd be sweet! The use case right now is that our security team has noticed that using simple auth over plain ldap:// is sending the credentials cleartext (which makes sense) but we wanted to avoid having to require ldaps:// for all connections so the starttls came up as an option to provide a secure connection even over ldap:// . I tried to set the `ca` in the tlsOptions to use one of our self-signed certs (mostly just a desperation attempt) but the connection but the connection was still clear text. Is there another combination of tlsOptions that would yield the same result? Thanks very much

**Comment by jgeurts** [comment]
hmm, I'm not sure I understand fully. Am I correct that you want the bind operation to be sent over ldaps://, but not other operations like search?

For what it's worth, if the url starts with ldaps://, then by default port 636 is used and the socket is created using tls.connect(), rather than net.connect(). All subsequent communication takes place using the socket, so if a secure connection is established initially, it will be used for the lifecycle of the client.

As far as options specified for `tlsOptions`, you may want to look into [tls.connect options](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) and [tls.createSecureContext options](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) to see what is passed through to `tls.connect()`

**Comment by thomascmurphy** [comment]
Oh yeah the ldaps:// communication works fine, the StartTls is just a way to provide the secure communication (still over :389 and with the normal ldap protocol) when ldaps isn't set up on the LDAP server itself. Using the starttls option in ldapjs seems to do the trick: we pass it a cert to use for the encryption and it (from what I can see in the source code anyway) does a tls.connect() with that connection. It just seems like a useful thing for ldapts since only the simple auth is available, as a way to provide another option for secure communication even when ldaps isn't available.

**Comment by jgeurts** [comment]
ah, I see the case it's missing now. What if I add `secure` to the options passed to the `Client` constructor?

That way, you could do something like: 

```ts
const client = new Client({
  url: 'ldap://...',
  port: 389,
  secure: true,
  tlsOptions: {
    ...
  },
});
```

**Comment by jgeurts** [comment]
Or I could infer that it's secure if tlsOptions are passed and might be able to avoid adding an explicit `secure` property

**Comment by thomascmurphy** [comment]
Ah that's true. I am definitely not an ldap expert but I would think that if a user passed in a cert to the tlsoptions they would want it to be secure? Either way would work fine for us. I'm not sure if there's anything more involved with the starttls beyond the connection that you open, I know that in ldapjs you have to make an explicit call to `starttls(...tlsOptions)` before you bind so it might require another call to the server.

**Comment by jgeurts** [comment]
Looks like ldapjs replaces the internal socket with the secure one when starttls() is called. I'll push out an update to use a secure socket when `tlsOptions` is specified, regardless of url or port. Hopefully that works for you!

**Comment by thomascmurphy** [comment]
sweet, I'll test it out. Thanks very much!

**Comment by jgeurts** [comment]
v2.1.0 has that update. Please let me know if you still have troubles!

**Comment by thomascmurphy** [comment]
This does not seem to be working for me (at least in the same way that the ldapjs stuff is working). Just updated and am using: 

```
new Client({
      url: port ? `${hostUrl}:${port}` : hostUrl,
      tlsOptions: {
        rejectUnauthorized: false,
        ca: [fs.readFileSync(certLocation)]
      }
    });
```

but am getting `Client network socket disconnected before secure TLS connection was established` (this was the same cert that I was using to test the ldapjs starttls). I think there may be more involved that simply opening the tls connection. From what I could see on wireshark there was an initial call to the ldap server to starttls (https://ldapwiki.com/wiki/StartTLS) before the bind happened.

**Comment by jgeurts** [comment]
my apologies! I completely missed that startTLS was an extended operation... working on adding that now

**Comment by jgeurts** [comment]
Ok, please give v2.2 a shot. I added `startTLS()` and some tests

**Comment by thomascmurphy** [comment]
Huzzah! I just tried it out and it seems to be working well, thanks so much for your help!

**Comment by jgeurts** [comment]
🎉 

Great, glad it worked!
