### ISSUE TITLE
Add Buffer as second parameter for extended operation

### ISSUE THREAD

**Issue by guenthergmbh** [ldapts/ldapts#74]
Can we change:
`public async exop(oid: string, value?: string, controls?: Control|Control[])`
to:
`public async exop(oid: string, value?: string | Buffer, controls?: Control|Control[])`?

In ExtendedRequest.ts Buffer as value is allowed, as per definition it should also be allowed in Client.ts for the calling method?

**Comment by jgeurts** [comment]
Fixed in v2.4.0
