### ISSUE TITLE
startTLS error

### ISSUE THREAD

**Issue by SBits2019** [ldapts/ldapts#81]
I am not sure if I am doing this correctly, I was not able to find any example code to do this.

I would like to use the `startTLS` extended operation to establish a secure connection to my ldap server and then bind the uname/pwd to authenticate a user.

I get the following error
`{ Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1095:19)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ECONNRESET',
  path: undefined,
`
Here is my code (the variables are declared in the file, not adding here)

```
const getLdap = async () => {
  const client = new Client({
    url: url,
    connectTimeout: 5000,
    tlsOptions: {
      rejectUnauthorized: tlsOpts.rejectUnauthorized,
      ca: [fs.readFileSync(tlsOpts.cert)],
    },
  });

  await client.startTLS(tlsOpts, (err) => {
    try {
      client.bind(searchDN, password);
      const { searchEntries } = client.search(searchDN, searchOpts);
      console.log(searchEntries[0].memberOf);
      return searchEntries[0].memberOf;
    } catch (err) {
      throw err.message;
    } finally {
      client.unbind();
    }
  });
};

```

**Comment by stiller-leser** [comment]
@SBits2019 How did you resolve the issue?
