### ISSUE TITLE
Allow retrieval of raw attribute value in search results without ;binary attribute option

### ISSUE THREAD

**Issue by BytewaveMLP** [ldapts/ldapts#82]
As mentioned in [my comment](https://github.com/ldapts/ldapts/issues/11#issuecomment-657163638) on #11, OpenLDAP doesn't return attribute data when requesting attributes with the `;binary` attribute option in searches unless those attributes are explicitly encodable with BER. Unfortunately, attributes like `jpegPhoto` do not meet this requirement, and it seems to be impossible to coax OpenLDAP into just dealing with it. This means that the trick this library employs to return `Buffer`s for binary attributes in searches fails, as specifying option `attributes: ['jpegPhoto']` returns a corrupt UTF-16 string, but `attributes: ['jpegPhoto;binary']` returns no attribute data whatsoever.

It would be nice to have, say, a `.raw` property on attribute values in search entries which would hold their value as the pre-`toString`ed `Buffer` holding the attribute data.

Related: #72 (sort of a duplicate?)

**Comment by jgeurts** [comment]
Should be able to explicitly specify which attributes should return as Buffer now. Please let me know if that is an acceptable solution for you!

```
const searchResult = await client.search('ou=Users,o=5be4c382c583e54de6a3ff52,dc=jumpcloud,dc=com', {
  filter: '(mail=peter.parker@marvel.com)',
  explicitBufferAttributes: ['jpegPhoto'],
});
```

**Comment by BytewaveMLP** [comment]
This is perfect, thank you! Just tested with my project, and I'm able to get the JPEG out of LDAP now.

Thank you for the quick fix! ❤️

**Comment by jgeurts** [comment]
Great, thanks for verifying!

**Comment by ppedro1** [comment]
This seems to resolve my problem with parsing objectGUIDs also. Could/should this be included in the documentation also? :)
