### ISSUE TITLE
Concurrent searches ('ldaps' protocol) with node > v12

### ISSUE THREAD

**Issue by mbornath** [ldapts/ldapts#83]
## Expected Behavior

When performing more than two search operations simultanously, every single one should resolve correctly.

## Actual Behavior

Only the first two search operations are resolved (Even though the ldap server answers correctly). 

This does only occur with node.js >= v12.

It does not occur with only two concurrent search operations.

From our ldap server logs, we can see, that the server sends everything correctly.

The same problem occurs with ldapjs (v2.0.0) as well.

```bash
Error: SearchRequest: Operation timed out (Client.ts:826:25)
```

## Steps to Reproduce

With this script you can reproduce the issue. We perform the same base search operation 3 times in parallel with `Promise.all`. 

It doesn't matter if we use 3 different search operations but for simplicities sake we use a base search with our bindDN as base to be sure the entry exists.

If you run this script with i.e. node v10, everything works as expected, with node v12 or higher you will see the error message after the operation has timed out.

```js
import { Client } from 'ldapts'
import assert from 'assert'

async function main() {
  const url = 'ldaps://...'
  const bindDN = 'cn=...'
  const bindCredentials = 'secret'

  const client = new Client({
    url,
    // since the operation times out, we use a low timeout
    timeout: 5000,
    connectTimeout: 5000,
  })

  try {
    await client.bind(bindDN, bindCredentials)

    const results = await Promise.all([
      findByDN(client, bindDN),
      findByDN(client, bindDN),
      findByDN(client, bindDN),
    ])

    assert.deepEqual(
      results.map((result) => result.dn),
      [bindDN, bindDN, bindDN],
    )

    console.log('ldapts is compatible with the selected Node version.')
  } catch (err) {
    console.log('ldapts is not compatible with the selected Node version.')
    console.error(err)
  } finally {
    await client.unbind()

    process.exit()
  }
}

async function findByDN(client, dn) {
  const { searchEntries } = await client.search(dn, {
    scope: 'base',
  })

  assert.equal(searchEntries.length, 1)

  console.log(`found ${searchEntries[0].dn}`)

  return searchEntries[0]
}

main()

```

## Context (Environment)

- NetIQ eDirectory version: 9.2.2
- node.js version: v12 or higher
- ldapts version: v2.6.1

**Comment by jgeurts** [comment]
Thank you for the detailed error report! [I added a test to](https://github.com/ldapts/ldapts/blob/master/tests/Client.tests.ts#L351-L387), I hope, cover your issue, but [I do not see the same behavior as you do](https://github.com/ldapts/ldapts/actions/runs/241809142). Please let me know if I'm missing something or if there's another way that I could reproduce the behavior!

**Comment by mbornath** [comment]
Thank you for your efforts. I could reproduce that the searches are working with the ldap server that you used in your tests. After further investigation we found out, that the problem exists only for e-Directory. So the problem has nothing to do with ldapts or ldapjs. Sorry for the inconvenience and thanks again. You can close this issue.

**Comment by jgeurts** [comment]
Sounds good, if you're able to analyze the network traffic and come up with a patch that fixes things, please let me know and I'm happy to add it to the library!
