### ISSUE TITLE
Unhandled promise rejection - Error: AddRequest: Operation timed out

### ISSUE THREAD

**Issue by ctaschereau** [ldapts/ldapts#88]
Package Version: 2.7.0 (but also tested with 1.9.0 and the bug is still present)
Node: 14
AD protocol: ldaps

If for some reason we attempt to add a user with a **null** password, we get an unhandled promise rejection even if we catch the "add" error. I tried listening on the client.socket's events, but that did not help in any way. Although this can be prevented higher up in our code, it seems like _ldapts_ should not fail in this way ...

Also, I tried to unbind the client in the try-finally, but that just resulted in a completely different error (Error: Connection closed before message response was received. Message type: AddRequest (0x68)) which I think might be pretty much related.

Here is the minimal snippet I used to reproduce this bug :

```
const { Client } = require('ldapts');

const client = new Client({
	url: 'ldaps://openldap:636',
	timeout: 5000,
	connectTimeout: 5000,
});

let entry = {
	cn: 'firstname  lastname',
	objectclass: ['organizationalPerson', 'person', 'inetOrgPerson', 'top'],
	pwdReset: 'TRUE',
	givenName : 'firstname',
	sn : 'lastname',
	mail : 'test@test.com',
	uid : 'test@test.com',
	userPassword : null, // This is the problem, leaving this undefined works as expected
};

let dn = `uid=${entry.uid},ou=Users,dc=test,dc=com`;

const doStuff = async() => {
	try {
		await client.bind(process.env.LDAP_DN, process.env.LDAP_PASSWORD);
		await client.add(dn, entry);
		console.log('I added my entry');
	} finally {
		//await client.unbind(); // This just fails differently...
	}
}

doStuff().then().catch(console.error);

```

**Comment by jgeurts** [comment]
Thanks for reporting this! v2.8.1 should have a fix for this. If it doesn't solve it as you expected, please let me know!
