### ISSUE TITLE
SASL external with TLS client certs

### ISSUE THREAD

**Issue by thernstig** [ldapts/ldapts#89]
I added a similar request/question to ldapjs but thought I'd ask here as well, since this seems better maintained. I've read the issues and docs and am pretty sure this is not supported, but wanted to check anyway.

I need to use LDAP (as a client) over ldaps:// where the tlsOptions contain a key and cert for TLS client authentication. I.e. the LDAP server (the peer) will verify my LDAP client via TLS client authentication.

But I want this TLS client auth to be used with the "SASL EXTERNAL mechanism" (page 29 in https://docs.ldap.com/specs/rfc4422.txt).
As far as I can understand, this is something I can currently achieve with ldapsearch by supplying the `-Y EXTERNAL`.

So with all that in mind, since ldapts already supports TLS using client cert/key, is it possible for it to use `-Y EXTERNAL` so that they are also used as the SASL mechanism "EXTERNAL"?

**Comment by jgeurts** [comment]
Thanks for reaching out and apologies on the late reply! New issues without an @jgeurts mention to me seem to not notify me. SASL will take a bit of work to hook up, but it should be doable... The main problem will be testing it as I don't have access to an ldap server that allows SASL authentication. If you are able to provide that, I would be happy to work on SASL. Otherwise, I can try releasing a beta and have you try it until we get it right.

**Comment by thernstig** [comment]
It would be amazing if you made this work. If you release a beta version, I surely could help verifying it. I cannot share the exact server we are using which is a private Dockerimage file. But it uses OpenLDAP in the background to create the server so I assume it can be achieved with OpenLDAP?

**Comment by thernstig** [comment]
@jgeurts Oh and if you can read Python code, then https://github.com/cannatag/ldap3 implements SASL.

**Comment by thernstig** [comment]
@jgeurts Did you think you had time to look at this? I am glad to help out verifying.

**Comment by jgeurts** [comment]
Could you please give v2.10.0 a shot? I tried to add SASL auth to bind(). Hopefully I got it right :)

```ts
await client.bind("EXTERNAL");
```

**Comment by thernstig** [comment]
I will give this a go and come back to you!

**Comment by thernstig** [comment]
@jgeurts I tested it and could not get it to work. I tried two things:

```js
const fsp = require('fs').promises;
const ldapts = require('ldapts');

(async () => {
  const key = await fsp.readFile('ldapkey.pem');
  const cert = await fsp.readFile('ldapcert.pem');
  const client = new ldapts.Client({
    url: 'ldap://0.0.0.0:8888',
    timeout: 0,
    connectTimeout: 0,
    strictDN: true,
    tlsOptions: {
      key,
      cert,
      rejectUnauthorized: false,
    },
  });

  let isAuthenticated;
  try {
    await client.bind('EXTERNAL');
    isAuthenticated = true;
  } catch (err) {
    console.log(err);
    isAuthenticated = false;
  } finally {
    await client.unbind();
  }
  console.log(isAuthenticated);
})();
```

This gave me:

```sh
SaslBindInProgressError: SASL(0): successful result:  Code: 0xe
    at Function.parse (/home/userA/code/projectA/server/node_modules/ldapts/StatusCodeParser.js:28:24)
    at Client.bind (/home/userA/code/projectA/server/node_modules/ldapts/Client.js:157:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/userA/code/projectA/server/ldap.js:25:5 {
  code: 14
}
false
```

I also tested this:

```js
const fsp = require('fs').promises;
const ldapts = require('ldapts');

(async () => {
  const key = await fsp.readFile('ldapkey.pem');
  const cert = await fsp.readFile('ldapcert.pem');
  const client = new ldapts.Client({
    url: 'ldap://0.0.0.0:8888',
    timeout: 0,
    connectTimeout: 0,
    strictDN: true,
    tlsOptions: {
      key,
      cert,
      rejectUnauthorized: false,
    },
  });

  let isAuthenticated;
  try {
    await client.bind('EXTERNAL', 'password');
    isAuthenticated = true;
  } catch (err) {
    console.log(err);
    isAuthenticated = false;
  } finally {
    await client.unbind();
  }
  console.log(isAuthenticated);
})();
```

This gave me:

```sh
InsufficientAccessError: SASL(-14): authorization failure: Inappropriate authentication Code: 0x32
    at Function.parse (/home/userA/code/projectA/server/node_modules/ldapts/StatusCodeParser.js:56:24)
    at Client.bind (/home/userA/code/projectA/server/node_modules/ldapts/Client.js:157:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/userA/code/projectA/server/ldap.js:21:5 {
  code: 50
}
false
```

There are a couple of things I do not understand about the API seen in the readme:

1. Why does SASL EXTERNAL allow for credentials such as `await client.bind("EXTERNAL", credentials);`? According to what I understood, using SASL EXTERNAL should never supply credentials.
2. In `await client.bind("EXTERNAL", credentials);` what did you really intend the credentials to be? I used a password but it makes no sense without a BIND DN as well.
3. The description says "The name (DN) of the directory object that the client wishes to bind as or the SASL mechanism (PLAIN, EXTERNAL". But if I use "PLAIN", a password is needed. Was that what the second code example was supposed to show? I.e. `await client.bind("PLAIN", credentials);` instead of `await client.bind("EXTERNAL", credentials);`?

**Comment by thernstig** [comment]
A good reference here https://ldap.com/the-ldap-bind-operation/ says:

> A SASL bind response may also include encoded server SASL credentials for use in subsequent processing. For a SASL mechanism that requires multiple request/response cycles, all responses except the last one will include a “SASL bind in progress” result code to indicate that the authentication process has not yet completed.

Does the SASL EXTERNAL require multiple request/response cycles? Could the error lie in the code there somewhere? I assume https://tools.ietf.org/html/rfc4513 and https://tools.ietf.org/html/rfc4422#appendix-A gives the best answers.

**Comment by thernstig** [comment]
@jgeurts Do you have any idea what might be wrong?

**Comment by jgeurts** [comment]
I've been looking through some of the documentation, but I don't readily see what should happen when `SaslBindInProgressError` is thrown. It seems like maybe the request should be made again, but I'm not 100%... without a server to test, I'm kind of shooting in the dark

**Comment by thernstig** [comment]
@jgeurts would https://github.com/cannatag/ldap3 maybe help? They have SASL support.
Starting from https://github.com/cannatag/ldap3/blob/dev/ldap3/protocol/sasl/external.py and https://github.com/cannatag/ldap3/blob/4d33166f0869b929f59c6e6825a1b9505eb99967/ldap3/protocol/sasl/sasl.py#L156

Yes, I do think that the request-response cycle is not completed in that case, as the text I quoted indicates. Does this help?
https://xmpp.org/extensions/xep-0178.html

Also did you read A.2 here https://tools.ietf.org/html/rfc4422#appendix-A ?

**Comment by jgeurts** [comment]
Please give v2.10.1 a shot. I removed a sequence id for the sasl details. The documentation wasn't super clear to me if it was needed or not and the value I had was based on an example I saw at https://ldap.com/ldapv3-wire-protocol-reference-bind/. If you still get SaslBindInProgressError, can you try calling `.bind()` again and see if that does anything? I apologize, this is pretty difficult for me to help with since I don't have a server to authenticate against. 

Even if you could capture the wire details from ldapsearch like what https://ldap.com/ldapv3-wire-protocol-reference-bind/ shows, that would help. 

I looked through the ldap3 python code, but nothing really stood out to me for what they're doing that this library isn't doing.

**Comment by thernstig** [comment]
Thanks @jgeurts I will make sure to test this tomorrow first thing.  I will try to grab some logs if I can as well if it fails.

**Comment by thernstig** [comment]
with version 2.10.1 this `await client.bind('EXTERNAL');` gives
```sh
AuthMethodNotSupportedError: unknown authentication method Code: 0x7
    at Function.parse (/home/etobher/code/cnom/server/node_modules/ldapts/StatusCodeParser.js:18:24)
    at Client.bind (/home/etobher/code/cnom/server/node_modules/ldapts/Client.js:157:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/etobher/code/cnom/server/ldap.js:27:5 {
  code: 7
}
```

**Comment by thernstig** [comment]
Does this help? I compared the server logs when using `ldapsearch` vs `ldapts`:

**ldapsearch**
```sh
5fce0736 conn=8484 fd=32 ACCEPT from IP=10.1.70.76:54042 (IP=0.0.0.0:1636)
5fce0736 conn=8484 fd=32 TLS established tls_ssf=256 ssf=256
5fce0736 conn=8484 op=0 BIND dn="" method=163
5fce0736 conn=8484 op=0 BIND authcid="cn=some-client" authzid="cn=some-client"
5fce0736 conn=8484 op=0 BIND dn="cn=authenticator,dc=la,dc=foo,dc=somecompany" mech=EXTERNAL sasl_ssf=0 ssf=256
5fce0736 conn=8484 op=0 RESULT tag=97 err=0 text=
5fce0736 conn=8484 op=1 SRCH base="" scope=2 deref=0 filter="(objectClass=*)"
5fce0736 conn=8484 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
5fce0736 conn=8484 op=2 UNBIND
5fce0736 conn=8484 fd=32 closed
```

**ldapts**
```sh
5fce02d7 conn=6915 fd=29 ACCEPT from IP=10.1.70.76:46414 (IP=0.0.0.0:1636)
5fce02d7 conn=6915 fd=29 TLS established tls_ssf=256 ssf=256
5fce02d7 conn=6915 op=0 BIND dn="" method=163
5fce02d7 conn=6915 op=0 RESULT tag=97 err=14 text=SASL(0): successful result:
5fce02d7 connection_operation: error: SASL bind in progress (tag=66).
5fce02d7 conn=6915 fd=29 closed
```

To note is that internally OpenLDAP maps the `cn=some-client` to `cn=authenticator`. So that `cn=authenticator` is most likely not coming from the client.

And here is output from ldapsearch with `-d 9`:
```sh
> LDAPTLS_CERT=ldapcert.pem LDAPTLS_KEY=ldapkey.pem LDAPTLS_REQCERT=never ldapsearch -H ldaps://0.0.0.0:8636 -Y EXTERNAL -d 9
ldap_url_parse_ext(ldaps://0.0.0.0:8636)
ldap_create
ldap_url_parse_ext(ldaps://0.0.0.0:8636/??base)
ldap_sasl_interactive_bind: user selected: EXTERNAL
ldap_int_sasl_bind: EXTERNAL
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 0.0.0.0:8636
ldap_new_socket: 3
ldap_prepare_socket: 3
ldap_connect_to_host: Trying 0.0.0.0:8636
ldap_pvt_connect: fd: 3 tm: -1 async: 0
attempting to connect:
connect success
ldap_int_sasl_open: host=myhost
SASL/EXTERNAL authentication started
ldap_sasl_bind
ldap_send_initial_request
ldap_send_server_request
ber_scanf fmt ({it) ber:
ber_scanf fmt ({i) ber:
ber_flush2: 26 bytes to sd 3
ldap_msgfree
ldap_result ld 0x55c94daee090 msgid 1
wait4msg ld 0x55c94daee090 msgid 1 (infinite timeout)
wait4msg continue ld 0x55c94daee090 msgid 1 all 1
** ld 0x55c94daee090 Connections:
* host: 0.0.0.0  port: 8636  (default)
  refcnt: 2  status: Connected
  last used: Mon Dec  7 14:53:48 2020


** ld 0x55c94daee090 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55c94daee090 request count 1 (abandoned 0)
** ld 0x55c94daee090 Response Queue:
   Empty
  ld 0x55c94daee090 response count 0
ldap_chkResponseList ld 0x55c94daee090 msgid 1 all 1
ldap_chkResponseList returns ld 0x55c94daee090 NULL
ldap_int_select
read1msg: ld 0x55c94daee090 msgid 1 all 1
ber_get_next
ber_get_next failed.
wait4msg continue ld 0x55c94daee090 msgid 1 all 1
** ld 0x55c94daee090 Connections:
* host: 0.0.0.0  port: 8636  (default)
  refcnt: 2  status: Connected
  last used: Mon Dec  7 14:53:48 2020


** ld 0x55c94daee090 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55c94daee090 request count 1 (abandoned 0)
** ld 0x55c94daee090 Response Queue:
   Empty
  ld 0x55c94daee090 response count 0
ldap_chkResponseList ld 0x55c94daee090 msgid 1 all 1
ldap_chkResponseList returns ld 0x55c94daee090 NULL
ldap_int_select
read1msg: ld 0x55c94daee090 msgid 1 all 1
ber_get_next
ber_get_next failed.
wait4msg continue ld 0x55c94daee090 msgid 1 all 1
** ld 0x55c94daee090 Connections:
* host: 0.0.0.0  port: 8636  (default)
  refcnt: 2  status: Connected
  last used: Mon Dec  7 14:53:48 2020


** ld 0x55c94daee090 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55c94daee090 request count 1 (abandoned 0)
** ld 0x55c94daee090 Response Queue:
   Empty
  ld 0x55c94daee090 response count 0
ldap_chkResponseList ld 0x55c94daee090 msgid 1 all 1
ldap_chkResponseList returns ld 0x55c94daee090 NULL
ldap_int_select
read1msg: ld 0x55c94daee090 msgid 1 all 1
ber_get_next
ber_get_next: tag 0x30 len 12 contents:
read1msg: ld 0x55c94daee090 msgid 1 message type bind
ber_scanf fmt ({eAA) ber:
read1msg: ld 0x55c94daee090 0 new referrals
read1msg:  mark request completed, ld 0x55c94daee090 msgid 1
request done: ld 0x55c94daee090 msgid 1
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_int_sasl_bind: EXTERNAL
ldap_parse_sasl_bind_result
ber_scanf fmt ({eAA) ber:
ldap_parse_result
ber_scanf fmt ({iAA) ber:
ber_scanf fmt (}) ber:
SASL username: cn=some-client
SASL SSF: 0
ldap_msgfree
# extended LDIF
#
# LDAPv3
# base <> (default) with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

ldap_search_ext
put_filter: "(objectclass=*)"
put_filter: simple
put_simple_filter: "objectclass=*"
ldap_send_initial_request
ldap_send_server_request
ber_scanf fmt ({it) ber:
ber_scanf fmt ({) ber:
ber_flush2: 39 bytes to sd 3
ldap_result ld 0x55c94daee090 msgid -1
wait4msg ld 0x55c94daee090 msgid -1 (infinite timeout)
wait4msg continue ld 0x55c94daee090 msgid -1 all 0
** ld 0x55c94daee090 Connections:
* host: 0.0.0.0  port: 8636  (default)
  refcnt: 2  status: Connected
  last used: Mon Dec  7 14:53:48 2020


** ld 0x55c94daee090 Outstanding Requests:
 * msgid 2,  origid 2, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55c94daee090 request count 1 (abandoned 0)
** ld 0x55c94daee090 Response Queue:
   Empty
  ld 0x55c94daee090 response count 0
ldap_chkResponseList ld 0x55c94daee090 msgid -1 all 0
ldap_chkResponseList returns ld 0x55c94daee090 NULL
ldap_int_select
read1msg: ld 0x55c94daee090 msgid -1 all 0
ber_get_next
ber_get_next: tag 0x30 len 12 contents:
read1msg: ld 0x55c94daee090 msgid 2 message type search-result
ber_scanf fmt ({eAA) ber:
read1msg: ld 0x55c94daee090 0 new referrals
read1msg:  mark request completed, ld 0x55c94daee090 msgid 2
request done: ld 0x55c94daee090 msgid 2
res_errno: 32, res_error: <>, res_matched: <>
ldap_free_request (origid 2, msgid 2)
# search result
search: 2
ldap_parse_result
ber_scanf fmt ({iAA) ber:
ber_scanf fmt (}) ber:
ldap_err2string
result: 32 No such object
ldap_msgfree

# numResponses: 1
ldap_free_connection 1 1
ldap_send_unbind
ber_flush2: 7 bytes to sd 3
ldap_free_connection: actually freed
```

**Comment by thernstig** [comment]
@jgeurts And to answer your question: I cannot do another bind request with ldapts since it throws with that error so I never reach any part below `await client.bind('EXTERNAL');`

**Comment by thernstig** [comment]
@jgeurts I found something that might help? Check here where someone explains how he implemented it for Golang:
https://stackoverflow.com/a/58288408

Here is the code: https://github.com/go-ldap/ldap/pull/232/files#diff-aade326d3512b5a2ada6faa791ddec468f2a0adedb352339c9e314e74c8949d2R118

**Comment by jgeurts** [comment]
Thank you for the additional info, I'm hoping it helps me wrap my head around sasl! It seems that ldapi (ldap over unix sockets) is somewhat related. I wasn't planning on supporting that - do you know if it's needed from your setup? I'll try to get back to looking into this later this week or next.

btw, you shouldn't need to @ mention me anymore. I think I resolved my notification issues

**Comment by thernstig** [comment]
It is not needed in my setup. I use `ldaps` to connect over TLS+TCP to a remove server (obviously TLS since that is what I want to use with SASL EXTERNAL 😄)

> btw, you shouldn't need to @ mention me anymore. I think I resolved my notification issues

Great!

**Comment by thernstig** [comment]
Did you get a chance to look into it? (also testing if not using @ works for you now).

**Comment by jgeurts** [comment]
I haven't had a chance yet, but on the plus side, the notification worked :)

**Comment by thernstig** [comment]
I noticed you merged https://github.com/ldapts/ldapts/commit/3763f0e66c5091fbe1f372088f85db22999481ed - does this mean I can try to test again?

> * Revert remove sequence identifier for SASL authentication

**Comment by jgeurts** [comment]
Unfortunately, no. This change just brings back the same behavior as what I had at the end of November

**Comment by thernstig** [comment]
@jgeurts this being open source and all, I completely understand and respect if you do not have time to try to add this functionality once yet again. Still, I'm kindly asking if you have the time. SASL auth will be a great use for any LDAP users since it's not that uncommon nowadays. (I am actually surprised not more users asked for this before).

**Comment by jgeurts** [comment]
Apologies for how long this has taken. I think ultimately, I’ll need a test server or docker image.

**Comment by thernstig** [comment]
@jgeurts Any chance you would like to give it a last chance without one? 🙏 I understand this is very hard to do. My project is propertiary, which means I cannot share it. The code in the Python project gives no great hints to follow-up on?

**Comment by jgeurts** [comment]
For sure, I haven't given up on this... It's just not super high on my priorities at this time. I will try to carve out some time to look into this some more. If, in the mean time, you're able to provide a docker image of OpenLDAP (or similar) setup to accept sasl, that would help immensely.

**Comment by thernstig** [comment]
@jgeurts I just googled and found this: https://hub.docker.com/r/bitnami/openldap/ - if you look at chapter _Securing OpenLDAP traffic_ it has an example there. It even has a docker compose file you can copy & paste early on that page, and then modify it to what is says in the _Securing OpenLDAP traffic_ chapter.

You should then be able to use ldapsearch with `-Y EXTERNAL` and the client certificates needed generated with the server CA.

**Comment by jgeurts** [comment]
@thernstig I wish the process was as simple as what you wrote, but it ended up being like the "draw the rest of the owl" meme, for me. 

That said, I have a docker image created, with certs. I have the GitHub action CI hooked up to load the OpenLDAP server and run a unit test that does a basic bind operation. However, I am very much not familiar with sasl. Can you please take what I have and write out explicitly how to use ldapsearch to do an external bind operation to the docker image? Or if it's missing something, please provide step by step directions of what needs to be done? 

Please see https://github.com/ldapts/ldapts/pull/95 for more details. Thanks!

**Comment by thernstig** [comment]
> @thernstig I wish the process was as simple as what you wrote, but it ended up being like the "draw the rest of the owl" meme, for me.

Haha 😆 I do appreciate the sense of humor though! I actually missed that meme and had too google, gave me a good chuckle.

Here are the exact commands I use, which works.
```sh
# With SASL External (using the TLS certificates authentication method)
LDAPTLS_CERT=certs/ldapcert.pem LDAPTLS_KEY=certs/ldapkey.pem LDAPTLS_CACERT=certs/ldapca.pem ldapsearch -H ldaps://hostname:636 -Y EXTERNAL -b "uid=admin,ou=people,dc=la,dc=orgname" '+' '*'

# Using the same certificates etc, but this time with normal authentication user/password
LDAPTLS_CERT=certs/ldapcert.pem LDAPTLS_KEY=certs/ldapkey.pem LDAPTLS_CACERT=certs/ldapca.pem ldapsearch -H ldaps://hostname:636 -D "uid=admin,ou=people,dc=la,dc=orgname" -w "asomepassword" '+' '*'
```

**Comment by thernstig** [comment]
Ping @jgeurts 😄 🚀

**Comment by thernstig** [comment]
Sorry to hear that, get well soon!

**Comment by thernstig** [comment]
@jgeurts did you manage to get back on your legs 😃 ?

**Comment by wattry** [comment]
Hi there,

I'm hope you've recovered from your burst appendix. We've been trying to find this functionality in nodejs for over 5 years. I was reading the python ldap docs provided by @thernstig and noticed the [external](https://ldap3.readthedocs.io/en/latest/ssltls.html?highlight=sasl#external) option credentials needs to be provided as such:

```python
If the bind operation does not work with:

sasl_credentials = None
you can try:

sasl_credentials = ''
```

So in the BindRequest.ts I modified the if statement to just set the password to the empty string  default and noticed that  my LDAPS request then worked. I'm not sure if it's a 100% fix however, it might be worth a try.

**Comment by wattry** [comment]
Can confirm this works exactly as we need it to.

**Comment by jgeurts** [comment]
The empty password change went out with v3.2.0. @thernstig, please let me know if that works for you or if you're still having troubles. Thanks @wattry!

**Comment by thernstig** [comment]
@jgeurts that is amazing, let me try this!

**Comment by wattry** [comment]
Just installed the package from npm and run the app. Still working for my ldaps request

**Comment by wattry** [comment]
@thernstig can this be closed?

**Comment by thernstig** [comment]
@wattry I have been on vacation, let me try to verify this tomorrow.

**Comment by wattry** [comment]
> @wattry I have been on vacation, let me try to verify this tomorrow.

Sounds good thanks @thernstig
