### ISSUE TITLE
how to limit connection time with LDAP server?

### ISSUE THREAD

**Issue by vadimkozin** [ldapts/ldapts#9]
The module works well! There is a question. If the LDAP server is available, then everything works, but if the LDAP server is not available (fell, does not respond to ping), then client.bind (...) waits a very long time. It would be nice to have the ability to set the maximum wait time for server availability

**Comment by adrianplavka** [comment]
So, you mean a connection timeout? 

I believe you can specify this timeout during creation of the `ldap.Client` through the ClientOptions (connectTimeout), which specifies "milliseconds client should wait before timing out on TCP connections".

**Comment by vadimkozin** [comment]
Thanks for the answer
I tried. here is my config
But it does not work (it waits for a very long time) if I change the working ip address to a fictional one, for example, to ldap://192.1.2.3:389
—
module.exports = {
    LDAP: {
        url : 'ldap://192.168.222.1:389',
        searchDN : 'dc=rss',
... ... ...
        clientOptions : {
            timeout: 3,
            connectTimeout: 5
        }
    }
}

**Comment by adrianplavka** [comment]
I've created a test project, but I couldn't reproduce your problem.

```javascript
import { Client } from "ldapts";

async function test() {
    const client = new Client({
        url: "ldap://192.168.222.1:389",
        connectTimeout: 5000,
        timeout: 5000,
    });

    try {
        console.time("time");
        await client.bind("non-existing");
    } catch (e) {
        console.timeEnd("time");
    }
}

test();
```

This bind fails & outputs roughly at the exact time, as specified in `connectTimeout`. I am using `v10.14.2` Node version.

What I've noticed, is that you think, that `timeout` & `connectTimeout` options are represented in seconds - but they're actually in milliseconds.

It seems, that you're using, or creating the client not in the right way. Can you check, if you are creating the client the same (or similar) way as above?

**Comment by vadimkozin** [comment]
Yes, you are right, I have a mistake. I entered everything into the config, but the line remained as it is: const client = new Client ({url}). I did not fix it. About seconds / milliseconds - this is the little things.
Thank you, it works.
