### ISSUE TITLE
Example (or even elaboration) for creating a Control

### ISSUE THREAD

**Issue by benlye** [ldapts/ldapts#91]
I'm need to perform an LDAP query using an extended control. (Specifically, Active Directory using `1.2.840.113556.1.4.417`).

The documentation doesn't have any examples for creating a `Control` to pass to the search client.  I've tried a few things but can't figure it out on my own.

I found [this example](https://github.com/ldapjs/node-ldapjs/issues/381#issuecomment-525503221) for ldapjs but nothing similar works with ldapts.

Can you give any pointers for creating a `Control` object?

**Comment by jgeurts** [comment]
Yeah, that was not clear or easy to use at all... Version 2.9.0 changes the `Control` class to be public and adds a more useful constructor. You should be able to do the following:

```ts
const searchResult = await client.search(
  'dc=foobar,dc=com',
  {
    scope: 'sub',
    filter: '(isDeleted=*)',
  },
  new Control('1.2.840.113556.1.4.417'),
);
```

Also, apologies on the late reply with this. I'm still not getting new issues that do not directly @jgeurts mention me :(

**Comment by jgeurts** [comment]
Please let me know if things still do not work as expected and I'll be happy to work through it!

**Comment by benlye** [comment]
Awesome, thank you!

Only thing to add is that I had to add an explicit import for Control, so maybe it's worth showing that in the example?
`import {Control} from 'ldapts/controls/Control';`
