### ISSUE TITLE
FR: expose errors as part of API

### ISSUE THREAD

**Issue by soletan** [ldapts/ldapts#93]
I'd like to detect, whether some bind request is failing due to technical issues (like connection timeouts) or because of provided user DN/password being wrong. Currently I have to import the error classes from `ldapts/errors` for that. Is it possible to include the errors with the base API available from `ldapts` itself?

**Comment by jgeurts** [comment]
Yep! I'll include this in the next release

**Comment by jgeurts** [comment]
This should be fixed with 2.12.0. Please let me know if I got it wrong!
