### ISSUE TITLE
noisy log exposes secrets

### ISSUE THREAD

**Issue by soletan** [ldapts/ldapts#94]
When using your library it seems to log quite noisily whatever is going on. Basically, this might be a good idea. But when it comes to logging bind operations it is covering used passwords in cleartext which seems to be unnecessary not to say probable source for collecting a wide range of user credentials.

**Comment by jgeurts** [comment]
I will try to address this for the next release. Thanks for letting me know!

**Comment by jgeurts** [comment]
This should be fixed with 2.12.0. Please let me know if it's still leaking bind credentials
